# Build and Test Application ,
on: 
  push :
    branches : [main]
  pull_request : 
    branches: [main]

jobs :
  build_test :
    runs-on : ubuntu-latest
    steps :
        - name : Checkout code
          uses : actions/checkout@v4
        - name : Set Up Docker Buildx
          uses : docker/setup-buildx-action@v3
        - name : build image api for scanning
          run : docker build -t my-apps:1.0.0 -f ./api/Dokerfile
        - name : build image mongo for scanning
          run : docker build -t my-apps:1.0.0 -f ./Dokerfile
        
